spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/todo_app

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR



jwt:
  secret: TodoApplicationServerJwtSecretKey